boxes = [
  { :name => "DC01",  :ip => "{{ip_range}}.30", :box => "jborean93/WindowsServer2019", :os => "windows", :cpus => 2, :mem => 4000},
  { :name => "SRV01", :ip => "{{ip_range}}.31", :box => "jborean93/WindowsServer2019", :os => "windows", :cpus => 2, :mem => 4000}
]
